#!/bin/sh
#
# This script executes and stores the output of a jupyter notebook
#

file=$(readlink -f "$1")
dir=$(dirname "$file")
base=dirname "${file%.*}"
output="$dir"/"$base"_out.ipynb

jupyter nbconvert --execute --output="$output"
